### ISSUE TITLE
Size of checkbox and radiobutton vectors

### ISSUE THREAD

**Issue by lurbas** [alexjlockwood/adp-delightful-details#13]
checkbox vector `vd_checkable_checkbox_checked`, `vd_checkable_checkbox_unchecked` as well as
radiobutton vector `vd_checkable_radiobutton_checked`, `vd_checkable_radiobutton_unchecked` have size of `32dp` even though visible part fits `24dp` square 
Would it be possible to trim inside padding and make them consistent with all android icons size - `24dp`?
Thanks in advance for your reply.

**Comment by alexjlockwood** [comment]
I think these actually are consistent with how they are implemented in the framework. IIRC I copied them from the framework source code: https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/res/res/drawable/btn_checkbox_checked_mtrl.xml

**Comment by lurbas** [comment]
That's a bummer. I know checkbox in the framework in 32dp, but actually, that makes it harder to align with other icons. Anyway, I thought you made it with shapeshifter and have access to the source, so it would be easy to make the adjustments. Well, thanks again, I guess the issue can be closed now.

**Comment by alexjlockwood** [comment]
You could pretty easily change it using a `<group>` I think... i.e. instead of this:

```
<vector android:viewportWidth="32" android:viewportHeight="32">
  ...
</vector>
```

you could change it to this:

```
<vector android:viewportWidth="24" android:viewportHeight="24">
  <group android:translateX="-4" android:translateY="-4">
    ...
  </group>
</vector>
```

Then you could use avocado to simplify the result: https://github.com/alexjlockwood/avocado
