### ISSUE TITLE
<animated-vector> requires API level 21 (current min is 16)

### ISSUE THREAD

**Issue by wilburx9** [alexjlockwood/adp-delightful-details#4]
I getting these errors from <code>animated-vector</code>. I thought the support library supports vector animation on pre-lollipop?

**Comment by ThanosFisherman** [comment]
I'm also getting these errors on Android studio 2.3.3 but the app executes fine.

**Comment by alexjlockwood** [comment]
This was probably an Android Studio bug that has since been fixed. LMK if I am mistaken.
